export type HelpCard = {
  slug: string;
  title: string;
  category: "Driving" | "Work" | "Education" | "Travel" | "Care" | "Rights" | "Emergency";
  summary: string;
  whenToUse: string[];
  checklist: string[];
  keyLine: string;
  tags: string[];
};

export const HELP_CARD_CONCERNS = [
  "Driving licence renewal",
  "Job interview adjustments",
  "Starting school with disability",
  "Access to Work",
  "Flying with a wheelchair",
  "Wheelchair damaged by airline",
  "Emergency wheelchair breakdown",
  "Reasonable adjustments",
  "Care package review",
  "University disability support",
  "Public transport refusal",
  "Blue Badge and parking",
] as const;

export const HELP_CARDS: HelpCard[] = [
  {
    slug: "section-88-driving-card",
    title: "Section 88 driving checklist",
    category: "Driving",
    summary: "Carry this when driving while your UK licence renewal is being processed.",
    whenToUse: [
      "You have applied to renew your licence with DVLA.",
      "You need to keep driving lawfully while waiting for decision.",
    ],
    checklist: [
      "Confirm you have submitted your valid renewal application.",
      "Check your doctor has not told you to stop driving.",
      "Confirm you still meet previous licence conditions.",
      "Carry proof of application date and reference number.",
      "Carry key line below in case questioned by employer or police.",
    ],
    keyLine:
      "I am driving under Section 88 provisions while my licence renewal is under DVLA review and I continue to meet medical and legal requirements.",
    tags: ["DVLA", "Section 88", "Licence", "Renewal"],
  },
  {
    slug: "job-interview-adjustments-card",
    title: "Job interview access card",
    category: "Work",
    summary: "Prompt card for disabled candidates to ask the right access questions before and after interview.",
    whenToUse: [
      "Before a first interview.",
      "When disclosing access needs to recruiter or hiring manager.",
    ],
    checklist: [
      "Ask who owns adjustments process and timelines.",
      "Ask whether interview location is step-free and toilet accessible.",
      "Ask for alternative formats or extra processing time if needed.",
      "Ask for occupational health referral timeline after offer.",
      "Ask how Access to Work support will be handled.",
      "Ask if fire evacuation plan (PEEP) will be created on day one.",
    ],
    keyLine:
      "I can perform this role with reasonable adjustments. Please confirm the named contact and timeline for adjustments, occupational health, Access to Work, and evacuation planning.",
    tags: ["Interview", "Adjustments", "Occupational health", "PEEP"],
  },
  {
    slug: "access-to-work-setup-card",
    title: "Access to Work setup card",
    category: "Work",
    summary: "Use this when starting work or changing role to avoid delays in support.",
    whenToUse: ["New job offer accepted.", "Role or location changes."],
    checklist: [
      "Start application early and keep reference numbers.",
      "Document barriers by task, not diagnosis.",
      "Agree employer contact and procurement route.",
      "List required equipment, support worker, travel support.",
      "Set review date after first 6-8 weeks in role.",
    ],
    keyLine: "Please confirm who submits quotes, who purchases items, and the target date support will be live.",
    tags: ["Access to Work", "Employer", "Support"],
  },
  {
    slug: "workplace-peep-risk-card",
    title: "Workplace risk and evacuation card",
    category: "Work",
    summary: "Checklist to trigger safe workplace setup for disabled staff.",
    whenToUse: ["First week in a new workplace.", "Office move or floor change."],
    checklist: [
      "Request workstation and access risk assessment.",
      "Request personal emergency evacuation plan (PEEP).",
      "Confirm who provides evacuation support and backup.",
      "Confirm refuge areas, exits, and drills include you.",
      "Review after any health or workplace change.",
    ],
    keyLine: "Safety planning must include my access needs in normal work and emergency evacuation.",
    tags: ["Risk assessment", "PEEP", "Fire", "Safety"],
  },
  {
    slug: "school-start-parent-card",
    title: "Parent school start access card",
    category: "Education",
    summary: "For parents of disabled children starting school or changing year group.",
    whenToUse: ["Before term starts.", "Transition meetings."],
    checklist: [
      "Ask for named SEND and safeguarding contacts.",
      "Ask for mobility, toileting, and medical support plan.",
      "Ask what risk assessments already exist and who updates them.",
      "Ask for written plan for trips, PE, and break times.",
      "Ask how exclusions and behaviour policy are adjusted for disability.",
      "Set first review meeting date in writing.",
    ],
    keyLine: "Please provide written support, risk assessment ownership, and review dates before start.",
    tags: ["School", "SEND", "Parent", "Support plan"],
  },
  {
    slug: "school-risk-assessment-card",
    title: "School risk assessment card",
    category: "Education",
    summary: "Quick checklist of risk assessments families should ask to see.",
    whenToUse: ["Annual review.", "New equipment or mobility needs."],
    checklist: [
      "Classroom access and movement plan.",
      "Manual handling and transfer safety plan.",
      "Toileting and intimate care procedure.",
      "Medical administration and emergency medication plan.",
      "School trip and transport risk assessment.",
      "Emergency evacuation and lockdown inclusion plan.",
    ],
    keyLine: "Please confirm each assessment owner, next review date, and where the plan is stored.",
    tags: ["Risk assessments", "Education", "Safety"],
  },
  {
    slug: "university-support-card",
    title: "University support setup card",
    category: "Education",
    summary: "Bring to disability service meetings to lock in practical support.",
    whenToUse: ["Before term starts.", "When support is failing."],
    checklist: [
      "Confirm disability advisor and escalation route.",
      "Confirm lecture, exam, and deadline adjustments.",
      "Confirm campus route and accommodation access.",
      "Confirm note-taking or communication support.",
      "Confirm what is DSA funded vs university funded.",
    ],
    keyLine: "Please send my support plan in writing and confirm who implements each adjustment.",
    tags: ["University", "DSA", "Adjustments"],
  },
  {
    slug: "flight-assistance-card",
    title: "Flying with wheelchair card",
    category: "Travel",
    summary: "Use before travel and at airport to reduce avoidable failures.",
    whenToUse: ["Booking flights.", "Check-in and boarding."],
    checklist: [
      "Provide wheelchair dimensions, weight, battery details in advance.",
      "Ask for written confirmation of assistance booking.",
      "Carry handling instructions for your wheelchair.",
      "Photograph wheelchair condition before handover.",
      "Ask how and where wheelchair is returned on landing.",
    ],
    keyLine: "My wheelchair is mobility equipment, not standard baggage. Please follow handling instructions and confirm return point.",
    tags: ["Airport assistance", "Wheelchair", "Airline"],
  },
  {
    slug: "wheelchair-damage-claim-card",
    title: "Wheelchair damage on flight card",
    category: "Travel",
    summary: "Immediate steps if airline damages mobility equipment.",
    whenToUse: ["At destination airport after damage.", "During claim process."],
    checklist: [
      "Report damage before leaving airport and get written report.",
      "Take timestamped photos and video evidence.",
      "Request immediate mobility replacement support.",
      "Keep receipts for emergency transport and equipment.",
      "Escalate through airline complaint route and regulator where relevant.",
    ],
    keyLine:
      "My wheelchair damage affects mobility and independence. I need immediate usable replacement support and a formal written claim reference.",
    tags: ["Damage claim", "CAA", "FAA", "Mobility equipment"],
  },
  {
    slug: "public-transport-refusal-card",
    title: "Bus and taxi refusal rights card",
    category: "Rights",
    summary: "For access refusals on public transport and taxi services.",
    whenToUse: ["Refused boarding.", "Driver refuses ramp or service."],
    checklist: [
      "Record operator name, route, time, and vehicle ID.",
      "Record exact refusal wording if possible.",
      "Request complaint reference immediately.",
      "Escalate to operator accessibility team in writing.",
      "Escalate to regulator or local authority licensing team if unresolved.",
    ],
    keyLine: "Please log this as a disability access refusal and provide a complaint reference now.",
    tags: ["Transport", "Refusal", "Complaint", "Equality Act"],
  },
  {
    slug: "blue-badge-parking-card",
    title: "Blue Badge parking quick card",
    category: "Driving",
    summary: "Parking rights and practical checks for disabled drivers and passengers.",
    whenToUse: ["Parking in unfamiliar area.", "Disputed use of badge."],
    checklist: [
      "Display badge and clock correctly where required.",
      "Check local restrictions and exemptions.",
      "Keep renewal and eligibility notes in phone/wallet.",
      "Record details if challenged or penalized unfairly.",
      "Appeal with evidence and timeline.",
    ],
    keyLine: "I am using this Blue Badge in line with local disabled parking rules. Please provide written reason for any penalty.",
    tags: ["Blue Badge", "Parking", "Appeal"],
  },
  {
    slug: "care-review-card",
    title: "Care package review card",
    category: "Care",
    summary: "Use at social care reviews to keep support matched to real needs.",
    whenToUse: ["Annual review.", "Needs have changed."],
    checklist: [
      "List what is unsafe or no longer manageable.",
      "Show impact on washing, toileting, meals, mobility, medication.",
      "Request reassessment of hours and outcomes.",
      "Request carer impact and backup planning review.",
      "Ask for written decision and appeal route.",
    ],
    keyLine: "My needs have changed and current support is no longer safe or sufficient. I request reassessment with written outcome.",
    tags: ["Social care", "Review", "Reassessment"],
  },
  {
    slug: "hospital-discharge-access-card",
    title: "Hospital discharge access card",
    category: "Care",
    summary: "Checklist to avoid unsafe discharge without support in place.",
    whenToUse: ["Before discharge day.", "After major health event."],
    checklist: [
      "Confirm home access and transfer safety plan.",
      "Confirm required equipment delivery date.",
      "Confirm medication and follow-up appointments in writing.",
      "Confirm who to call if support fails in first 48 hours.",
      "Do not accept unsafe discharge without clear plan.",
    ],
    keyLine: "I need a safe discharge plan with equipment, support contacts, and written actions before leaving hospital.",
    tags: ["Discharge", "Hospital", "Safety"],
  },
  {
    slug: "emergency-breakdown-card",
    title: "Wheelchair breakdown emergency card",
    category: "Emergency",
    summary: "Fast actions when wheelchair or key equipment fails in public.",
    whenToUse: ["Wheelchair breakdown.", "Battery or control failure."],
    checklist: [
      "Move to safe location and avoid unsafe manual lifting.",
      "Call repair provider and note reference.",
      "Request emergency mobility backup support.",
      "Contact venue/transport staff for immediate practical help.",
      "Record incident details for complaints or support claims.",
    ],
    keyLine: "I need safe immediate mobility support while urgent repair is arranged.",
    tags: ["Breakdown", "Emergency", "Repair"],
  },
  {
    slug: "reasonable-adjustments-card",
    title: "Reasonable adjustments request card",
    category: "Rights",
    summary: "Universal card for work, education, and services.",
    whenToUse: ["Requesting adjustment.", "Following up ignored request."],
    checklist: [
      "State barrier clearly and where it happens.",
      "State requested adjustment and why it helps.",
      "Ask for implementation owner and date.",
      "Ask for decision in writing.",
      "Escalate if delayed or refused without reason.",
    ],
    keyLine: "I am requesting a reasonable adjustment to remove this barrier. Please confirm decision and implementation date in writing.",
    tags: ["Equality Act", "Adjustments", "Access"],
  },
  {
    slug: "travel-insurance-disability-card",
    title: "Accessible travel insurance card",
    category: "Travel",
    summary: "Questions to ask before buying travel insurance with disability.",
    whenToUse: ["Buying policy.", "Declaring medical conditions."],
    checklist: [
      "Confirm declared conditions are fully listed.",
      "Confirm wheelchair/mobility equipment coverage amount.",
      "Confirm emergency assistance access needs are noted.",
      "Confirm replacement equipment process abroad.",
      "Save policy wording and emergency numbers offline.",
    ],
    keyLine: "Please confirm in writing that my condition and mobility equipment are covered under this policy.",
    tags: ["Insurance", "Travel", "Wheelchair"],
  },
];
