import type { HelpCardPack, HelpCardSource, ResearchHelpCard } from "@/features/help-cards/helpCardTypes";

const LAST_REVIEWED = "2026-06-09";

const DEFAULT_ACTIONS = {
  canCopy: true,
  canPrint: true,
  canSaveToPhone: true,
  canTailorWithAI: true,
} as const;

function source(
  title: string,
  publisher: string,
  url: string,
  supports: string,
  confidence: HelpCardSource["confidence"] = "official",
): HelpCardSource {
  return { title, publisher, url, lastChecked: LAST_REVIEWED, confidence, supports };
}

export const RESEARCH_HELP_CARDS: ResearchHelpCard[] = [
  {
    id: "section-88-driving-licence",
    slug: "section-88-driving-licence",
    title: "Section 88 driving licence explanation",
    category: "Police & driving",
    situation: "Stopped while DVLA is processing a licence application",
    urgency: "high",
    badge: "Police & driving",
    summary:
      "Calm script for when your licence application is with DVLA and you need to explain that Section 88 may apply.",
    useThisWhen:
      "You are stopped or challenged while your licence application is with DVLA and you need a calm way to explain that Section 88 may apply.",
    quickLine:
      "I understand I may be able to drive under Section 88 only if all DVLA conditions apply. My application is with DVLA, and I can show what evidence I have.",
    keyBullets: [
      "Section 88 is conditional.",
      "DVLA says you and your doctor/healthcare professional are best placed to consider whether the criteria apply.",
      "Do not rely on this card if your licence was refused/revoked, you are disqualified, your application is over a year old, or you have been told not to drive.",
    ],
    sayThisFirst: [
      "I do not have my current licence because my application is with DVLA.",
      "I understand Section 88 may apply only if the DVLA conditions are met.",
      "I can show evidence that my application is with DVLA.",
      "I am happy to provide my details so this can be checked.",
    ],
    whatToAskFor: [
      "Time to explain calmly.",
      "A chance to show evidence of the DVLA application.",
      "A chance to explain any medical/licensing context accurately.",
    ],
    questionsToAsk: [
      "Can you explain what information you need from me?",
      "Can you record that my application is currently with DVLA?",
      "Would you like my DVLA reference or previous licence details?",
      "Can I show my application evidence?",
    ],
    evidenceToHaveReady: [
      "DVLA application confirmation.",
      "DVLA letter/email or reference.",
      "Previous licence details.",
      "Proof of identity.",
      "Medical advice/fitness-to-drive evidence if relevant.",
      "Any DVLA form or renewal confirmation.",
    ],
    afterTheConversation: [
      "Record date, time, officer details and what was said.",
      "Keep copies of any notes or references given.",
      "Follow up with DVLA if you receive conflicting information.",
    ],
    importantLimits: [
      "This card is not legal advice.",
      "This card does not prove you can drive.",
      "You may only be able to drive if all Section 88 criteria apply.",
      "Do not drive if DVLA has refused or revoked your licence.",
      "Do not drive if you have been disqualified.",
      "Do not drive if your doctor or healthcare professional has advised you not to drive.",
      "Do not rely on Section 88 if your application is more than one year old.",
      "Section 88 is UK legislation and may not be accepted abroad.",
      "Always check DVLA guidance and your own medical/licensing situation.",
    ],
    sources: [
      source(
        "Can I drive while my application is with DVLA? (INF188/6)",
        "Driver and Vehicle Licensing Agency",
        "https://www.gov.uk/government/publications/inf1886-can-i-drive-while-my-application-is-with-dvla",
        "Section 88 criteria and when cover may end.",
      ),
      source(
        "INF188/6: Can I drive while my application is with DVLA? (PDF)",
        "Driver and Vehicle Licensing Agency",
        "https://assets.publishing.service.gov.uk/media/64edcf3a13ae1500116e2f5d/inf1886-can-i-drive-while-my-application-is-with-dvla.pdf",
        "Official DVLA guidance on Section 88 conditions.",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["DVLA", "Section 88", "Driving", "Police"],
  },
  {
    id: "equality-act-reasonable-adjustments",
    slug: "equality-act-reasonable-adjustments",
    title: "Equality Act reasonable adjustments",
    category: "Rights & complaints",
    situation: "Asking an organisation to remove or reduce a disability-related barrier",
    urgency: "medium",
    badge: "Rights & complaints",
    summary:
      "Ask a service, workplace, venue or provider to adjust how they do something because you are disabled or have a health condition.",
    useThisWhen:
      "You need to ask a service, workplace, venue, healthcare provider, council, transport provider or other organisation to adjust how they do something because you are disabled or have a health condition.",
    quickLine: "I'm asking for a reasonable adjustment because without it I'm put at a substantial disadvantage.",
    keyBullets: [
      "Reasonable adjustments can include changing a process, changing a physical feature, or providing support/auxiliary aids.",
      "What is reasonable depends on the situation.",
      "Ask for the adjustment in writing where possible.",
    ],
    sayThisFirst: [
      "I'm disabled / I have a health condition that affects how I access this service.",
      "Without an adjustment, I'm put at a substantial disadvantage.",
      "I'm asking for a reasonable adjustment so I can access this fairly.",
      "Please confirm what you can do and who is responsible for arranging it.",
    ],
    keyRightsLine:
      "Under the Equality Act 2010, organisations may have a duty to make reasonable adjustments where a disabled person would otherwise be placed at a substantial disadvantage.",
    whatToAskFor: [
      "A change to the usual process.",
      "Step-free access or an accessible route.",
      "Accessible toilet information.",
      "Accessible parking/drop-off.",
      "Extra time.",
      "A quieter space.",
      "Written information.",
      "Communication support.",
      "Permission for a PA/carer/support person.",
      "Alternative appointment format.",
      "Equipment or support.",
      "Confirmation in writing.",
    ],
    questionsToAsk: [
      "Who is responsible for arranging the adjustment?",
      "Can you confirm this by email?",
      "What alternative can you offer if the first option is not available?",
      "Is there a named contact on the day?",
      "Can you record this adjustment for future visits?",
    ],
    evidenceToHaveReady: [
      "Short access-needs summary.",
      "Medical or disability evidence if relevant.",
      "Photos or examples of the barrier.",
      "Previous adjustment examples.",
      "Emails/messages confirming what was requested.",
    ],
    afterTheConversation: [
      "Record date, time, person spoken to and what was agreed.",
      "Send a follow-up email confirming the request.",
      "Keep screenshots or copies of replies.",
      "If refused, ask for the reason in writing and whether alternatives were considered.",
    ],
    importantLimits: [
      "This card is not legal advice.",
      "Whether an adjustment is legally reasonable depends on the circumstances.",
      "Do not state that an organisation has definitely broken the law unless you have taken advice.",
      "Keep requests specific and practical.",
    ],
    sources: [
      source(
        "Equality Act 2010, Section 20: Duty to make adjustments",
        "legislation.gov.uk",
        "https://www.legislation.gov.uk/ukpga/2010/15/section/20",
        "Statutory duty to make reasonable adjustments.",
      ),
      source(
        "Equality Act 2010: guidance",
        "Government Equalities Office",
        "https://www.gov.uk/guidance/equality-act-2010-guidance",
        "Overview of Equality Act protections and duties.",
      ),
      source(
        "Disability: quick start guide for service providers",
        "Government Equalities Office",
        "https://www.gov.uk/government/publications/equality-act-guidance/disability-quick-start-guide-for-service-providers-html",
        "Service provider reasonable adjustment duties and examples.",
      ),
      source(
        "Reasonable adjustments for workers with disabilities or health conditions",
        "UK Government",
        "https://www.gov.uk/reasonable-adjustments-for-disabled-workers",
        "Employment reasonable adjustments guidance.",
      ),
      source(
        "Reasonable adjustments at work",
        "ACAS",
        "https://www.acas.org.uk/reasonable-adjustments",
        "Employer duty and examples for applicants and workers.",
        "official",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["Equality Act", "Reasonable adjustments", "Rights"],
  },
  {
    id: "job-interview-reasonable-adjustments",
    slug: "job-interview-reasonable-adjustments",
    title: "Job interview reasonable adjustment card",
    category: "Work & interviews",
    situation: "Preparing for a job interview or recruitment process",
    urgency: "medium",
    badge: "Work & interviews",
    summary:
      "Request interview changes such as extra time, accessible room setup, remote interview, communication support or PA/carer support.",
    useThisWhen:
      "You have a job interview and need changes such as extra time, accessible room setup, remote interview, communication support, rest breaks, parking, accessible toilet access or PA/carer support.",
    quickLine: "I'm asking for reasonable adjustments so I can take part in the interview fairly.",
    keyBullets: [
      "Reasonable adjustments can apply to job applicants.",
      "Adjustments can include changes to recruitment processes.",
      "Ask early and get confirmation in writing.",
    ],
    sayThisFirst: [
      "Thank you for inviting me to interview.",
      "I'm looking forward to taking part.",
      "I need to request reasonable adjustments so I can participate fairly.",
      "Please confirm the arrangements in writing before the interview.",
    ],
    keyRightsLine:
      "GOV.UK and ACAS guidance explain that reasonable adjustments can apply to job applicants, including changes to recruitment processes and interview arrangements.",
    whatToAskFor: [
      "Step-free interview location.",
      "Interview room accessible for a wheelchair or mobility aid.",
      "Accessible toilet nearby.",
      "Accessible parking or drop-off point.",
      "Extra time for written or reading tasks.",
      "Rest breaks.",
      "Remote interview option.",
      "Questions or materials in accessible format.",
      "Communication support.",
      "Permission for PA/carer/support person where needed.",
      "Clear arrival instructions and named contact.",
    ],
    questionsToAsk: [
      "Is the interview room step-free?",
      "Is there an accessible toilet nearby?",
      "Where is the nearest accessible parking/drop-off?",
      "Will there be any written test, reading task or timed task?",
      "Can I have extra time or breaks if needed?",
      "Can the interview be remote if the building is not accessible?",
      "Who should I contact on arrival?",
    ],
    evidenceToHaveReady: [
      "Short access-needs summary.",
      "Medical/access evidence if required.",
      "Previous adjustment examples.",
      "Email request and reply.",
      "Travel/access notes.",
    ],
    afterTheConversation: [
      "Send follow-up email confirming agreed adjustments.",
      "Thank you for confirming the interview. To make sure I can take part fairly, please confirm the agreed reasonable adjustments and who I should contact on arrival.",
      "Keep copies of all recruiter replies.",
    ],
    importantLimits: [
      "This card is not legal advice.",
      "What is reasonable depends on the role, interview format and employer circumstances.",
      "Do not assume the employer knows your needs unless you tell them.",
      "Keep the request practical, specific and linked to the interview barrier.",
    ],
    sources: [
      source(
        "Reasonable adjustments for workers with disabilities or health conditions",
        "UK Government",
        "https://www.gov.uk/reasonable-adjustments-for-disabled-workers",
        "Recruitment and workplace adjustment examples.",
      ),
      source(
        "Reasonable adjustments at work",
        "ACAS",
        "https://www.acas.org.uk/reasonable-adjustments",
        "Applicant and employee adjustment duties.",
        "official",
      ),
      source(
        "Equality Act 2010, Section 20",
        "legislation.gov.uk",
        "https://www.legislation.gov.uk/ukpga/2010/15/section/20",
        "Statutory reasonable adjustment duty.",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["Interview", "Work", "Recruitment", "Reasonable adjustments"],
  },
  {
    id: "gp-hospital-appointment-access",
    slug: "gp-hospital-appointment-access",
    title: "GP / hospital appointment access card",
    category: "Healthcare appointments",
    situation: "Preparing for a GP, hospital or NHS appointment",
    urgency: "medium",
    badge: "Healthcare",
    summary:
      "Ask GP surgery, hospital or NHS service to record and meet your communication, mobility, sensory or access needs.",
    useThisWhen:
      "You need the GP surgery, hospital, clinic or NHS service to record and meet your communication, mobility, sensory or access needs.",
    quickLine:
      "Please record and flag my access and communication needs so staff know what support I need for appointments.",
    keyBullets: [
      "NHS/adult social care services should identify, record, flag, share, meet and review information and communication support needs.",
      "Examples can include longer appointments, accessible information, specific contact methods, communication support or advocacy.",
      "Ask for agreed adjustments to be recorded.",
    ],
    sayThisFirst: [
      "I have access/communication needs that affect appointments.",
      "Please record these on my record so staff know what support I need.",
      "Please confirm how these needs will be flagged for future appointments.",
      "I need the appointment to be accessible so I can understand, communicate and take part.",
    ],
    whatToAskFor: [
      "Longer appointment.",
      "Step-free route.",
      "Accessible toilet nearby.",
      "Quiet waiting area.",
      "Specific contact method, such as email or text instead of phone.",
      "Written information after the appointment.",
      "Large print, audio, easy read or accessible digital information.",
      "BSL/deafblind interpreter or communication professional if needed.",
      "PA/carer/support person present.",
      "Time to answer questions.",
      "Reasonable Adjustment Flag or record note if available.",
    ],
    questionsToAsk: [
      "Can you record my communication/access needs?",
      "Can these needs be flagged for future appointments?",
      "Can I have a longer appointment?",
      "Is there a step-free route and accessible toilet?",
      "Can appointment letters/results be sent in my accessible format?",
      "Can a carer/PA/support person come with me?",
      "Can you confirm this in writing?",
      "Can you please speak directly to me and give me time to answer?",
      "Can you write down the key decisions and next steps?",
    ],
    evidenceToHaveReady: [
      "Access-needs summary.",
      "Medication list.",
      "Current symptoms/concerns.",
      "Medical letters or care plan.",
      "Communication passport if available.",
      "Notes from PA/carer if relevant.",
      "Photos or measurements if access is physical.",
    ],
    afterTheConversation: [
      "Ask for written next steps.",
      "Ask who to contact if the adjustment was not met.",
      "Record what happened.",
      "Ask for the needs to be corrected/updated if they were wrong.",
    ],
    importantLimits: [
      "This card is not medical advice.",
      "It does not replace clinical advice.",
      "It is about access, communication and participation.",
      "Some adjustments may require advance notice, but services should still consider what can be done.",
    ],
    sources: [
      source(
        "Accessible Information Standard – requirements (DAPB1605)",
        "NHS England",
        "https://www.england.nhs.uk/long-read/accessible-information-standard-requirements-dapb1605/",
        "Requirements to identify, record and meet communication needs.",
      ),
      source(
        "Accessible Information Standard – implementation guidance",
        "NHS England",
        "https://www.england.nhs.uk/long-read/accessible-information-standard-implementation-guidance/",
        "How services should implement the standard.",
      ),
      source(
        "Reasonable adjustments",
        "NHS England",
        "https://www.england.nhs.uk/learning-disabilities/improving-health/reasonable-adjustments/",
        "Health service reasonable adjustment duties.",
      ),
      source(
        "Reasonable Adjustment Flag",
        "NHS Digital",
        "https://digital.nhs.uk/services/reasonable-adjustment-flag",
        "Recording adjustments on NHS records.",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["NHS", "GP", "Hospital", "Communication"],
  },
  {
    id: "social-care-assessment-preparation",
    slug: "social-care-assessment-preparation",
    title: "Social care assessment preparation card",
    category: "Social care",
    situation: "Preparing for a council adult social care needs assessment",
    urgency: "medium",
    badge: "Social care",
    summary:
      "Explain your daily living needs, risks, support needs and outcomes during a social services needs assessment.",
    useThisWhen:
      "You have a needs assessment with social services and need to explain your daily living needs, risks, support needs and outcomes.",
    quickLine:
      "I need the assessment to look at what support I need to live safely, manage daily life and achieve my outcomes.",
    keyBullets: [
      "A needs assessment looks at what help and support you need.",
      "Support can include help at home, equipment, adaptations, day services or care.",
      "Do not understate what happens on bad days or when unpaid support is not available.",
    ],
    sayThisFirst: [
      "I need this assessment to cover what I can and cannot do safely.",
      "Please consider my needs across the whole day and night, not just one short snapshot.",
      "Please include the risks if support is not provided.",
      "Please send me the assessment and any care/support plan in writing.",
    ],
    whatToAskFor: [
      "Washing/bathing support needs recorded.",
      "Dressing/undressing support needs recorded.",
      "Toileting/continence support needs recorded.",
      "Eating/drinking/meal preparation support recorded.",
      "Medication/treatment support recorded.",
      "Transfers, mobility and night-time needs recorded.",
      "Communication and community access needs recorded.",
      "Outcomes: safety, injury prevention, carer sustainability.",
    ],
    questionsToAsk: [
      "What needs have you recorded?",
      "What risks have you recorded?",
      "What outcomes are being assessed?",
      "What support options are being considered?",
      "Will equipment/adaptations/direct payments/home care be considered?",
      "Can I have the assessment and decision in writing?",
      "What happens if I disagree?",
      "Can my carer have a carer's assessment?",
    ],
    evidenceToHaveReady: [
      "Care diary.",
      "Examples of what happens without support.",
      "Medical letters.",
      "OT/physio reports.",
      "District nurse notes if relevant.",
      "Photos of access barriers.",
      "Falls/injury/pressure-care records.",
      "Current support plan.",
      "PA/carer rota or gaps.",
      "Carer statement.",
    ],
    afterTheConversation: [
      "Ask for a copy of the assessment.",
      "Ask for the eligibility decision and reasons.",
      "Ask for the proposed care/support plan.",
      "Check whether risks and night-time needs are recorded.",
      "Correct anything inaccurate in writing.",
      "Keep a copy of all emails and notes.",
    ],
    importantLimits: [
      "This card is not legal advice.",
      "It does not guarantee a care package or number of hours.",
      "Assessment outcomes depend on the council's decision and the evidence recorded.",
      "Be specific about risks, frequency, duration and consequences.",
    ],
    sources: [
      source(
        "Apply for a needs assessment by social services",
        "UK Government",
        "https://www.gov.uk/apply-needs-assessment-social-services",
        "What a needs assessment covers in England and Wales.",
      ),
      source(
        "Getting a care needs assessment",
        "NHS",
        "https://www.nhs.uk/social-care-and-support/help-from-social-services-and-charities/getting-a-needs-assessment/",
        "How to request a council needs assessment.",
      ),
      source(
        "The Care Needs Assessment Explained",
        "Age UK",
        "https://www.ageuk.org.uk/information-advice/care/arranging-care/care-needs-assessment/",
        "Practical preparation for assessments.",
        "secondary",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["Social care", "Assessment", "Council"],
  },
  {
    id: "pip-benefits-assessment",
    slug: "pip-benefits-assessment",
    title: "PIP / benefits assessment card",
    category: "Benefits & assessments",
    situation: "Preparing for PIP form, review or assessment",
    urgency: "medium",
    badge: "Benefits & assessments",
    summary:
      "Explain how your condition affects daily living and mobility for a PIP claim, review or assessment.",
    useThisWhen:
      "You are preparing for a PIP claim, review or assessment and need to explain how your condition affects daily living and mobility.",
    quickLine:
      "PIP looks at how my condition affects daily living and mobility tasks, including whether I can do them safely, repeatedly, to an acceptable standard and in a reasonable time.",
    keyBullets: [
      "Focus on what happens when you try to do the activity.",
      "Explain help, aids, prompting, supervision, risk, pain, fatigue and time taken.",
      "Give real examples, not just diagnosis labels.",
    ],
    sayThisFirst: [
      "I want to explain how my condition affects daily living and mobility.",
      "Please consider whether I can do each activity safely, repeatedly, to an acceptable standard and in a reasonable time.",
      "I need to explain what happens on bad days, after exertion and when support is not available.",
    ],
    whatToAskFor: [
      "Time to explain each daily living and mobility activity.",
      "Consideration of reliability: safely, acceptably, repeatedly, in reasonable time.",
      "Consideration of help from another person, prompting, supervision or aids.",
      "Consideration of pain, fatigue and risk after activity.",
    ],
    questionsToAsk: [
      "Can you explain which activities you are asking about?",
      "Can I describe what happens on bad days?",
      "Can I explain whether I can repeat the activity later the same day?",
      "Can I include examples of accidents, falls or unsafe attempts?",
    ],
    evidenceToHaveReady: [
      "Recent medical evidence.",
      "Medication/treatment list.",
      "Care/support plan.",
      "OT/physio reports.",
      "Diary of difficult days.",
      "Examples of accidents, falls, choking, fatigue, pain or unsafe attempts.",
      "Statements from carers, PA, family or professionals.",
      "Photos of aids/adaptations if relevant.",
      "Appointment letters or reports.",
    ],
    afterTheConversation: [
      "Write down what was asked and what you said.",
      "Record any problems with the assessment.",
      "Keep copies of evidence sent.",
      "Check the decision letter carefully when it arrives.",
      "Ask for advice if you disagree with the decision.",
    ],
    importantLimits: [
      "This card is not benefits advice or legal advice.",
      "It does not mean you qualify for PIP.",
      "PIP decisions depend on the evidence, descriptors and DWP decision-making.",
      "Do not exaggerate, but do not understate the impact either.",
      "Use specific real examples.",
    ],
    sources: [
      source(
        "Personal Independence Payment (PIP)",
        "Department for Work and Pensions",
        "https://www.gov.uk/pip",
        "What PIP assesses in daily living and mobility.",
      ),
      source(
        "PIP assessment guide part 2: the assessment criteria",
        "Department for Work and Pensions",
        "https://www.gov.uk/government/publications/personal-independence-payment-assessment-guide-for-assessment-providers/pip-assessment-guide-part-2-the-assessment-criteria",
        "Reliability criteria: safely, acceptably, repeatedly, reasonable time.",
      ),
      source(
        "How your disability affects you: PIP2 form and information booklet",
        "Department for Work and Pensions",
        "https://assets.publishing.service.gov.uk/media/6602af72f1d3a09b1f32ac81/pip2-form-and-information-booklet__1_.pdf",
        "Official form guidance on describing impact.",
      ),
      source(
        "How the DWP makes a decision on PIP claims",
        "Citizens Advice",
        "https://www.citizensadvice.org.uk/benefits/sick-or-disabled-people-and-carers/pip/help-with-your-claim/how-decisions-are-made/",
        "Plain-English explanation of decision-making.",
        "secondary",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["PIP", "Benefits", "DWP", "Assessment"],
  },
  {
    id: "venue-access-questions",
    slug: "venue-access-questions",
    title: "Venue access questions card",
    category: "Venues & travel",
    situation: "Checking access before visiting a venue",
    urgency: "medium",
    badge: "Venues & travel",
    summary:
      "Get clear answers about step-free access, toilets, parking, seating, sensory needs or staff assistance before you visit.",
    useThisWhen:
      "You are contacting a venue before visiting and need clear answers about step-free access, toilets, parking, seating, sensory needs or staff assistance.",
    quickLine: "Please confirm the access details in writing so I can plan safely before I visit.",
    keyBullets: [
      "Ask specific questions, not just “is it accessible?”",
      "Check entrance, route, toilet, parking, seating and staff assistance.",
      "Ask for photos or measurements if access is uncertain.",
    ],
    sayThisFirst: [
      "I'm planning a visit and need to check access before I travel.",
      "Please can you confirm the details in writing?",
      "A general 'yes, we are accessible' is not enough for me to plan safely.",
    ],
    whatToAskFor: [
      "Step-free entrance and route details.",
      "Doorway widths and turning space for wheelchair.",
      "Accessible toilet location and features.",
      "Blue Badge parking and drop-off information.",
      "Quieter visiting times and seating while waiting.",
      "Staff assistance and named contact on arrival.",
    ],
    questionsToAsk: [
      "Is there a step-free entrance?",
      "Are there any steps, lips, slopes or thresholds?",
      "What is the narrowest doorway on the route?",
      "Is there an accessible toilet? Is it step-free and kept unlocked?",
      "Is there Blue Badge parking? How far from the entrance?",
      "Is there a quieter time to visit or a quiet space?",
      "Can staff help with doors, route directions or queue management?",
      "Can I bring a PA/carer/support person?",
      "Can you send photos of the entrance and route?",
    ],
    evidenceToHaveReady: [
      "Venue email or message confirming access.",
      "Screenshots of access information.",
      "Photos sent by the venue.",
      "Name of staff member who confirmed.",
      "Date/time of confirmation.",
      "Any access issue experienced on arrival.",
    ],
    afterTheConversation: [
      "Save written confirmation before travelling.",
      "Record any access problems on arrival.",
      "Ask what reasonable alternative the venue can offer if access fails.",
    ],
    importantLimits: [
      "This card is not legal advice.",
      "Access information can change.",
      "Always confirm directly before travelling if access is critical.",
      "Do not rely only on generic website claims.",
      "If access is not available, ask what reasonable alternative the venue can offer.",
    ],
    sources: [
      source(
        "Disability: quick start guide for service providers",
        "Government Equalities Office",
        "https://www.gov.uk/government/publications/equality-act-guidance/disability-quick-start-guide-for-service-providers-html",
        "Service provider access duties.",
      ),
      source(
        "Equality Act 2010, Section 20",
        "legislation.gov.uk",
        "https://www.legislation.gov.uk/ukpga/2010/15/section/20",
        "Reasonable adjustment duty for venues.",
      ),
      source(
        "Duty to make reasonable adjustments for disabled people",
        "Citizens Advice",
        "https://www.citizensadvice.org.uk/law-and-courts/discrimination/check-what-type-of-discrimination-youve-experienced/duty-to-make-reasonable-adjustments-for-disabled-people/",
        "Plain-English explanation of adjustment duties.",
        "secondary",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["Venue", "Access", "Travel", "Planning"],
  },
  {
    id: "blue-badge-issue",
    slug: "blue-badge-issue",
    title: "Blue Badge issue card",
    category: "Police & driving",
    situation: "Blue Badge parking challenge or PCN",
    urgency: "high",
    badge: "Police & driving",
    summary:
      "Record the facts calmly when challenged about Blue Badge parking or when you receive a PCN.",
    useThisWhen:
      "You are challenged about Blue Badge parking, or you receive a PCN and need to record the facts calmly.",
    quickLine:
      "I understand a Blue Badge is not a licence to park anywhere. Please explain which restriction you say applies so I can record it accurately.",
    keyBullets: [
      "Always check signs and local rules.",
      "Badge and clock must be displayed correctly where required.",
      "Take photos and keep evidence if challenged.",
    ],
    sayThisFirst: [
      "I am a Blue Badge holder.",
      "I understand I must follow the rules and check signs.",
      "Please explain which parking restriction you say applies.",
      "I would like to record the details so I can respond properly.",
    ],
    whatToAskFor: [
      "Clear explanation of which sign or restriction applies.",
      "Time to photograph badge display, clock, signs and markings.",
      "Written details of challenge or PCN process.",
    ],
    questionsToAsk: [
      "Which sign or restriction applies here?",
      "Is this council-enforced, private, or another type of car park?",
      "Can you show me where the relevant restriction is displayed?",
      "What is the appeal or challenge process?",
      "Can I have the details in writing?",
    ],
    evidenceToHaveReady: [
      "Photos of badge display.",
      "Photos of clock display.",
      "Photos of signs and road markings.",
      "Wider photos showing location/context.",
      "PCN/ticket number.",
      "Time and date.",
      "Name/ID of officer if available.",
      "Any relevant access need or reason for parking there.",
    ],
    afterTheConversation: [
      "Keep all photos and PCN details.",
      "Follow the council or operator appeal process.",
      "Contact the relevant local council for Blue Badge scheme questions.",
    ],
    importantLimits: [
      "This card is not legal advice.",
      "A Blue Badge is not a licence to park anywhere.",
      "You must check signs, local rules and car park rules.",
      "Off-street/private car parks can have different rules.",
      "Do not misuse a badge or allow someone else to use it for their own benefit.",
      "Contact the relevant local council for Blue Badge scheme questions.",
    ],
    sources: [
      source(
        "The Blue Badge scheme: rights and responsibilities in England",
        "Department for Transport",
        "https://www.gov.uk/government/publications/the-blue-badge-scheme-rights-and-responsibilities-in-england/the-blue-badge-scheme-rights-and-responsibilities-in-england",
        "Badge display, parking rules and limits.",
      ),
      source(
        "Blue Badge rights and responsibilities booklet (PDF)",
        "Department for Transport",
        "https://assets.publishing.service.gov.uk/media/611a22aed3bf7f63a54f5fad/blue-badge-rights-and-responsibility-large-type.pdf",
        "Official booklet on badge use and restrictions.",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["Blue Badge", "Parking", "PCN"],
  },
  {
    id: "communication-support-card",
    slug: "communication-support-card",
    title: "Communication support card",
    category: "Communication cards",
    situation: "When you need more time, written information, support or accessible communication",
    urgency: "high",
    badge: "Communication",
    summary:
      "Ask someone to speak clearly, give you more time, write things down, or allow a PA/carer/support person to help.",
    useThisWhen:
      "You need someone to speak clearly, give you more time, speak directly to you, write things down, use a different contact method, or allow a PA/carer/support person to help.",
    quickLine: "Please give me time to respond and communicate with me in a way I can access and understand.",
    keyBullets: [
      "Speak directly to me.",
      "Give me time.",
      "Write down key decisions.",
      "Allow my PA/carer/support person if needed.",
    ],
    sayThisFirst: [
      "Please speak directly to me.",
      "Please give me time to respond.",
      "Please do not rush or talk over me.",
      "I may need my PA/carer/support person to help me communicate.",
      "Please write down key decisions or next steps.",
    ],
    whatToAskFor: [
      "More time to respond.",
      "Written information.",
      "Email/text instead of phone.",
      "Large print, easy read, audio or accessible digital format.",
      "Shorter questions, one at a time.",
      "Plain English.",
      "Breaks.",
      "PA/carer/support person present.",
      "BSL/interpreter/communication professional if needed.",
      "Confirmation of decisions in writing.",
    ],
    questionsToAsk: [
      "Can you write that down?",
      "Can you send that by email?",
      "Can you repeat the question more slowly?",
      "Can you ask one question at a time?",
      "Can my PA/carer support communication?",
      "Can this communication need be recorded for next time?",
    ],
    evidenceToHaveReady: [
      "Written summary.",
      "Appointment notes.",
      "Emails/messages.",
      "Name of person spoken to.",
      "Record of any communication barrier.",
      "Any existing communication passport.",
    ],
    afterTheConversation: [
      "Ask for written summary of decisions.",
      "Record any communication barriers experienced.",
      "Request that needs are recorded for next contact.",
    ],
    importantLimits: [
      "This card is not medical or legal advice.",
      "It explains communication support needs.",
      "In healthcare/adult social care, the Accessible Information Standard is especially relevant.",
      "In other services, reasonable adjustment duties may be relevant under the Equality Act.",
    ],
    sources: [
      source(
        "Accessible Information Standard – requirements",
        "NHS England",
        "https://www.england.nhs.uk/long-read/accessible-information-standard-requirements-dapb1605/",
        "Communication support requirements in NHS/social care.",
      ),
      source(
        "Accessible Information Standard – implementation guidance",
        "NHS England",
        "https://www.england.nhs.uk/long-read/accessible-information-standard-implementation-guidance/",
        "How to meet communication needs.",
      ),
      source(
        "Disability: quick start guide for service providers",
        "Government Equalities Office",
        "https://www.gov.uk/government/publications/equality-act-guidance/disability-quick-start-guide-for-service-providers-html",
        "Auxiliary aids and communication support as adjustments.",
      ),
      source(
        "Equality Act 2010, Section 20",
        "legislation.gov.uk",
        "https://www.legislation.gov.uk/ukpga/2010/15/section/20",
        "Reasonable adjustment duty.",
      ),
    ],
    actions: DEFAULT_ACTIONS,
    lastReviewed: LAST_REVIEWED,
    sourceConfidence: "official",
    tags: ["Communication", "Accessible information", "Support"],
  },
];

export const HELP_CARD_PACKS: HelpCardPack[] = [
  {
    id: "job-interview-access-pack",
    title: "Job interview access pack",
    description: "Interview adjustments, rights framing, and communication support for recruitment.",
    cardSlugs: [
      "job-interview-reasonable-adjustments",
      "equality-act-reasonable-adjustments",
      "communication-support-card",
    ],
  },
  {
    id: "medical-appointment-access-pack",
    title: "Medical appointment access pack",
    description: "NHS appointment access needs and communication support.",
    cardSlugs: ["gp-hospital-appointment-access", "communication-support-card"],
  },
  {
    id: "social-care-assessment-pack",
    title: "Social care assessment pack",
    description: "Prepare for council needs assessments with clear outcomes and evidence.",
    cardSlugs: ["social-care-assessment-preparation", "communication-support-card"],
  },
  {
    id: "venue-visit-access-pack",
    title: "Venue visit access pack",
    description: "Plan venue visits, confirm access in writing, and handle parking challenges.",
    cardSlugs: [
      "venue-access-questions",
      "equality-act-reasonable-adjustments",
      "communication-support-card",
      "blue-badge-issue",
    ],
  },
];

export const FEATURED_RESEARCH_CARD_SLUG = "job-interview-reasonable-adjustments";
